[package]
name = "falcon_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
num-complex = "0.4"
rustfft = "6.1.0"

[lib]
path = "src/lib.rs"
