[package]
name = "falcon_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.4"
num-complex = "0.4.4"
lazy_static = { version = "1.4.0", features = [] }

[lib]
path = "src/lib.rs"
